name = "sudipta-dutta-portfolio"
compatibility_date = "2026-09-06"
pages_build_output_dir = "."

[[d1_databases]]
binding = "VISITOR_COUNTER_DB"
database_name = "sudipta-portfolio-visitor-counter"
database_id = "f9cee238-024d-4335-9440-02121ec48066"
